### ISSUE TITLE
Crashing when get called with no name.

### ISSUE THREAD

**Issue by RussellZornes** [marcguilera/dart_dependencies#1]
Cannot get a binding with no name.
```
builder.bindSingleton(SettingsBloc());
Injector injector = builder.build();

```
Crash when I call get.
`SettingsBloc bloc = injector.get<SettingsBloc>();
`

**Comment by marcguilera** [comment]
Thanks! 
What version of dart are you using? What error do you get? Can you reproduce with `master`?

**Comment by RussellZornes** [comment]
You fixed it with the Unit Tests commit. It was with _registration_container.dart.
Thanks!

**Comment by marcguilera** [comment]
Glad it fixed it for you. Will push `0.0.2` shortly. Thanks for testing this out.

**Comment by marcguilera** [comment]
Feel free to use `0.0.2`, it's been pushed.
