### ISSUE TITLE
The superclass, 'Module', has no unnamed constructor that takes no arguments

### ISSUE THREAD

**Issue by AlexeyPoldeo** [marcguilera/dart_dependencies#2]
I'm using Flutter 1.0, please advise

<img width="587" alt="screen shot 2019-01-20 at 10 43 59" src="https://user-images.githubusercontent.com/20498870/51436546-5224cf80-1ca0-11e9-9edc-b1369286deda.png">

**Comment by marcguilera** [comment]
What version of the lib are you using? I am working on a Flutter specific example.

**Comment by marcguilera** [comment]
Feel free to check this out if you are using flutter:
https://medium.com/@marcguilera/dependency-injection-in-flutter-625650195a98

**Comment by bhm** [comment]
Snippet of code in the readme shows `class PlayerModule extends Module {` just like in the screenshot above. While it should be `implements` like in all snippets in Medium article, or code samples in repo.
